#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Практика 8: Демонстрация восстановления данных
"""

def main():
    print()
    print("┌" + "─" * 60 + "┐")
    print("│  ПРАКТИКАЛЫҚ ЖҰМЫС 8: Деректерді Қалпына Келтіру     │")
    print("└" + "─" * 60 + "┘")
    print("=" * 62)
    print("Windows деректерді қалпына келтіру әдістері")
    print("=" * 62)
    print()
    
    # Recycle Bin
    print("=" * 62)
    print("1. RECYCLE BIN ҚАЛПЫНА КЕЛТІРУ")
    print("=" * 62)
    print()
    print("Іздеу орны: C:\\$Recycle.Bin")
    print()
    print("Табылған файлдар:")
    print("  1. DataLab.txt (12 KB, жойылды: 2024-01-15 14:23)")
    print("  2. report.docx (245 KB, жойылды: 2024-01-14 09:15)")
    print("  3. backup.zip (1.2 MB, жойылды: 2024-01-13 18:47)")
    print()
    print("✓ DataLab.txt қалпына келтірілді")
    print("✓ Файл орналасуы: C:\\Users\\User\\Documents\\")
    print("✓ Бүтіндігі тексерілді: OK")
    print()
    
    # File History
    print("=" * 62)
    print("2. FILE HISTORY НҰСҚАЛАРЫ")
    print("=" * 62)
    print()
    print("Файл: important_data.xlsx")
    print()
    print("Қолжетімді нұсқалар:")
    print("  1. 2024-01-15 10:00 - 234 KB")
    print("  2. 2024-01-14 15:30 - 231 KB")
    print("  3. 2024-01-13 11:20 - 228 KB")
    print("  4. 2024-01-12 16:45 - 225 KB")
    print()
    print("✓ Нұсқа 2 (2024-01-14 15:30) таңдалды")
    print("✓ Файл қалпына келтірілді")
    print("✓ Деректер тексерілді: сәтті")
    print()
    
    # System Restore
    print("=" * 62)
    print("3. SYSTEM RESTORE НҮКТЕЛЕРІ")
    print("=" * 62)
    print()
    print("Қалпына келтіру нүктелері:")
    print("  1. 2024-01-15 09:00 - Automatic Restore Point")
    print("  2. 2024-01-10 14:30 - Before Windows Update")
    print("  3. 2024-01-05 08:15 - Manual Restore Point")
    print()
    print("✓ Нүкте 2 (2024-01-10 14:30) таңдалды")
    print("✓ Жүйелік файлдар қалпына келтірілді")
    print("✓ Реестр қалпына келтірілді")
    print("✓ Жүйе қайта жүктелді")
    print()
    
    # Shadow Copy
    print("=" * 62)
    print("4. SHADOW COPY (VSS)")
    print("=" * 62)
    print()
    print("Volume: C:\\")
    print()
    print("Shadow копиялар:")
    print("  1. 2024-01-15 12:00 - 4.2 GB")
    print("  2. 2024-01-14 12:00 - 4.1 GB")
    print("  3. 2024-01-13 12:00 - 3.9 GB")
    print()
    print("✓ Shadow Copy 1 монтирован")
    print("✓ Файл project_data.db табылды")
    print("✓ Файл көшірілді")
    print("✓ Деректер базасы тексерілді: OK")
    print()
    
    # Recuva
    print("=" * 62)
    print("5. ТЕРЕҢ ҚАЛПЫНА КЕЛТІРУ (RECUVA)")
    print("=" * 62)
    print()
    print("Диск сканерлеуі: C:\\ (500 GB)")
    print("Сканерлеу тереңдігі: Deep scan")
    print()
    print("Прогресс: [████████████████████████] 100%")
    print()
    print("Табылған файлдар:")
    print("  ● Отлично (5 файлдар) - қалпына келтіруге дайын")
    print("  ● Жақсы (12 файлдар) - бүтін")
    print("  ● Нашар (8 файлдар) - бөлшектік бүлінген")
    print("  ● Жойылған (23 файлдар) - қалпына келмейді")
    print()
    print("✓ deleted_photo.jpg қалпына келтірілді (Отлично)")
    print("✓ old_document.pdf қалпына келтірілді (Жақсы)")
    print("✓ Файлдар сақталды: C:\\Recovered\\")
    print()
    
    print("=" * 62)
    print("✓ БАРЛЫҚ ДЕРЕКТЕР СӘТТІ ҚАЛПЫНА КЕЛТІРІЛДІ")
    print("=" * 62)
    print()
    print("Статистика:")
    print("  - Recycle Bin: 1 файл")
    print("  - File History: 1 файл")
    print("  - System Restore: жүйе қалпына келтірілді")
    print("  - Shadow Copy: 1 файл")
    print("  - Recuva: 2 файл")
    print()
    print("Жалпы қалпына келтірілген: 5 файл + жүйе")
    print()

if __name__ == "__main__":
    main()

